### PR TITLE
detect and use Enterprise WDK environment

### PR DESCRIPTION
**Pull request by fdetro**
This PR enables detection of a Enterprise WDK environment (https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/using-the-enterprise-wdk). If the EWDK environment is found, it is used for driver builds.

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
Looks good, thanks!

**Comment by DiskGetor** [comment]
i was tested,findwdk do not work for ewdk 2015,2017,can you release a example

**Comment by SergiusTheBest** [comment]
@DiskGetor Did you run `SetupBuildEnv.cmd` from EWDK?

**Comment by DiskGetor** [comment]
> @DiskGetor您是`SetupBuildEnv.cmd`从EWDK 运行的吗？

No, i load ewdk.iso to vmware,after run clion and set build tool as iso path... Not work so. Sorry my bad english.

**Comment by DiskGetor** [comment]
Some days ago I'd like to use ewdk build, but tested after i found the ewdk maybe not supposed like vs2017 cmake packge,finally the clion can't working,so ewdk is not my best choose.

**Comment by SergiusTheBest** [comment]
@DiskGetor You should run `SetupBuildEnv.cmd` in a console and than cmake or clion in the same console. So they will be run in the EWDK environment.

**Pull request merged**
