### PR TITLE
Fix the BUG that functions in intrin.h cannot be used even if it is i…

### PR DESCRIPTION
**Pull request by Oxygen1a1**
Fix the BUG that functions in intrin.h cannot be used even if it is include <intrin.h>

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
@Oxygen1a1 What exact function is not working? I'm trying to add a sample code to demonstrate the issue .

**Comment by Oxygen1a1** [comment]
> @Oxygen1a1 What exact function is not working? I'm trying to add a sample code to demonstrate the issue .

intrinsic function from <intrin.h>,like _disable()、_enable() and so on

**Comment by Oxygen1a1** [comment]
I have added the demonstrate of this issue and submitted it. hope you can accept this PR : ).

**Comment by SergiusTheBest** [comment]
@Oxygen1a1 That's weird as it compiles for me without any changes. What compiler do you use?

**Comment by Oxygen1a1** [comment]
> @Oxygen1a1 That's weird as it compiles for me without any changes. What compiler do you use?

I use vs2019 sdk&wdk version: 10.0.19041.0 with msvc complier

**Comment by SergiusTheBest** [comment]
@Oxygen1a1 Looks good! Thank you!

**Pull request merged**
